tasks:
  - name: blog
    input:
      name: '@mark-magic/plugin-joplin'
      config:
        baseUrl: 'http://127.0.0.1:41184'
        token: ${JOPLIN_TOKEN}
        tag: blog
    output:
      name: '@mark-magic/plugin-hexo'
